---
abstract: 'Automated SIGNATURE testing'
author:
  - 'Audrey Tang <cpan@audreyt.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Signature
no_index:
  directory:
    - inc
    - t
provides:
  Test::Signature:
    file: lib/Test/Signature.pm
    version: '1.11'
requires:
  Test::Builder: '0.17'
  Test::More: '0.47'
  perl: '5.005'
resources:
  license: http://dev.perl.org/licenses/
version: '1.11'
