--- 
abstract: Automated SIGNATURE testing
author: Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Test-Signature
no_index: 
  directory: 
    - inc
    - t
provides: 
  Test::Signature: 
    file: lib/Test/Signature.pm
    version: 1.10
requires: 
  Test::Builder: 0.17
  Test::More: 0.47
  perl: 5.004
version: 1.10
